### ISSUE TITLE
cluster_genera.py fails for one genus

### ISSUE THREAD

**Issue by uloeber** [rrwick/Bacsort#5]
Dear Ryan,
thanks for developing Bacsort. I'm trying to run it on a bunch of genomes from isolates and cluster_genera.py fails every time, but I can't interpret the error. Do you have any ideas or did anyone ran into that issue before?
Thanks in advance!

`Clustering Streptococcus
------------------------------------------------
Loading distances... found 6275 assemblies
Traceback (most recent call last):
  File "/home/xyz/Bacsort/scripts/cluster_genera.py", line 221, in <module>
    main()
  File "/home/xyz/Bacsort/scripts/cluster_genera.py", line 62, in main
    assemblies, graph = create_graph_from_distances(distance_filename, args.threshold, excluded)
  File "/home/xyz/Bacsort/scripts/cluster_genera.py", line 136, in create_graph_from_distances
    assert len(all_connections[assembly]) == assembly_count - 1
AssertionError`

**Comment by Nilad** [comment]
Same kind of error with Enteroroccus clade

# command
```
singularity exec -B /media/:/media/ ~/Bureau/Tools/Bacsort/Bacsort.simg  combine_distance_matrices.py tree/fastani.phylip tree/mash.phylip > tree/distances.phylip && singularity exec -B /media/:/media/ ~/Bureau/Tools/Bacsort/Bacsort.simg bionj_tree.R tree/distances.phylip tree/tree.newick
```
# log
```
This script will create a distance matrix using a combination of distances from
tree/fastani.phylip and tree/mash.phylip. Short distances will come from
tree/fastani.phylip and longer distances from tree/mash.phylip, with
intermediate distances a blend between the two. To ensure a smooth transition
between them, a linear regression will be used to adjust tree/mash.phylip
distances to match those from tree/fastani.phylip.

Loading tree/fastani.phylip (790 assemblies)....... done
Loading tree/mash.phylip (790 assemblies)....... done
Traceback (most recent call last):
  File "/usr/local/Bacsort/scripts/combine_distance_matrices.py", line 189, in <module>
    main()
  File "/usr/local/Bacsort/scripts/combine_distance_matrices.py", line 37, in main
    assert matrix_1_assemblies == matrix_2_assemblies
AssertionError
```
